// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, email, refresh_token, user_agent, ip_address, is_blocked, expires_at, created_at, last_active_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, user_id, email, refresh_token, user_agent, ip_address, is_blocked, expires_at, created_at, last_active_at
`

type CreateSessionParams struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Email        sql.NullString `json:"email"`
	RefreshToken string         `json:"refresh_token"`
	UserAgent    string         `json:"user_agent"`
	IpAddress    pqtype.Inet    `json:"ip_address"`
	IsBlocked    bool           `json:"is_blocked"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	LastActiveAt sql.NullTime   `json:"last_active_at"`
}

// Create a new session
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.RefreshToken,
		arg.UserAgent,
		arg.IpAddress,
		arg.IsBlocked,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.LastActiveAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

// Delete a session
func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getAllSessions = `-- name: GetAllSessions :many
SELECT id, user_id, email, refresh_token, user_agent, ip_address, is_blocked, expires_at, created_at, last_active_at FROM sessions
LIMIT $1
`

// Get all sessions with a limit
func (q *Queries) GetAllSessions(ctx context.Context, limit int32) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getAllSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.RefreshToken,
			&i.UserAgent,
			&i.IpAddress,
			&i.IsBlocked,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT id, user_id, email, refresh_token, user_agent, ip_address, is_blocked, expires_at, created_at, last_active_at FROM sessions
WHERE user_id = $1
`

// Get sessions by user ID
func (q *Queries) GetSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.RefreshToken,
			&i.UserAgent,
			&i.IpAddress,
			&i.IsBlocked,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET user_id = $1, email = $2, refresh_token = $3, user_agent = $4, ip_address = $5, is_blocked = $6, expires_at = $7, created_at = $8, last_active_at = $9
WHERE id = $10 RETURNING id, user_id, email, refresh_token, user_agent, ip_address, is_blocked, expires_at, created_at, last_active_at
`

type UpdateSessionParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	Email        sql.NullString `json:"email"`
	RefreshToken string         `json:"refresh_token"`
	UserAgent    string         `json:"user_agent"`
	IpAddress    pqtype.Inet    `json:"ip_address"`
	IsBlocked    bool           `json:"is_blocked"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	LastActiveAt sql.NullTime   `json:"last_active_at"`
	ID           uuid.UUID      `json:"id"`
}

// Update a session
func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.UserID,
		arg.Email,
		arg.RefreshToken,
		arg.UserAgent,
		arg.IpAddress,
		arg.IsBlocked,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.LastActiveAt,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}
