CREATE TABLE "user_logins" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "login_at" timestamptz,
  "ip_address" inet,
  "user_agent" varchar
);

CREATE TABLE "sessions" (
  "id" uuid PRIMARY KEY NOT NULL,
  "user_id" uuid NOT NULL,
  "email" varchar,
  "refresh_token" varchar NOT NULL, -- Update on token rotation. When trying to update or rotate token if token doesn't exist. Block all session and user account
  "user_agent" text NOT NULL,
  "ip_address" inet NOT NULL,
  "is_blocked" boolean NOT NULL,
  "is_breached" boolean NOT NULL, -- Identifies whether a security breached occurred from here leading to blocking of other sessions and user.
  "expires_at" timestamptz NOT NULL, -- Update on token rotation, When session/refresh token will end. This will logged the user out.
  "created_at" timestamptz, -- When session token was created
  "last_active_at" timestamptz -- Update on token rotation. Used to identify when last the user logged in
);


CREATE TABLE "security_questions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "question" varchar,
  "answer" varchar,
  "expired_at" timestamptz
);

-- TODO: check or remove
CREATE TABLE "banned_users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "banned_at" timestamptz,
  "reason" varchar
);

-- TODO: For more security concious app
CREATE TABLE "login_failures" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR NOT NULL,
  "timestamp" timestamptz,
  "user_agent" varchar,
  "ip_address" inet
);

CREATE INDEX ON "user_logins" ("user_id", "login_at");
CREATE INDEX ON "sessions" ("user_id", "expires_at");

CREATE INDEX ON "login_failures" ("email", "timestamp");

CREATE INDEX ON "banned_users" ("user_id");



ALTER TABLE "user_logins" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "login_failures" ADD FOREIGN KEY ("email") REFERENCES "users" ("email");

ALTER TABLE "banned_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "security_questions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");