ALTER TABLE "password_reset_requests" DROP CONSTRAINT IF EXISTS "password_reset_requests_email_fkey";
ALTER TABLE "two_factor_secrets" DROP CONSTRAINT IF EXISTS "two_factor_secrets_user_id_fkey";
ALTER TABLE "two_factor_revocation" DROP CONSTRAINT IF EXISTS "two_factor_revocation_user_id_fkey";
ALTER TABLE "two_factor_backup_codes" DROP CONSTRAINT IF EXISTS "two_factor_backup_codes_user_id_fkey";

-- Drop indexes
DROP INDEX IF EXISTS "password_reset_requests_email_expires_at_idx";

-- Drop tables
DROP TABLE IF EXISTS "two_factor_backup_codes";
DROP TABLE IF EXISTS "two_factor_revocation";
DROP TABLE IF EXISTS "two_factor_secrets";
DROP TABLE IF EXISTS "password_reset_requests";


CREATE TABLE "password_reset_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "email" varchar NOT NULL,
  "token" varchar NOT NULL UNIQUE,
  "used" boolean,
  "created_at" timestamptz, --DEFAULT (now()),
  "expires_at" timestamptz NOT NULL
);

CREATE TABLE "two_factor_secrets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "secret_key" varchar,
  "recovery_codes" json
);

CREATE TABLE "two_factor_revocation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "revoked_at" timestamptz
);

CREATE TABLE "two_factor_backup_codes" (
  "user_id" uuid,
  "code" varchar
);