CREATE TABLE "password_reset_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL,
  "token" varchar NOT NULL UNIQUE,
  "used" boolean,
  "created_at" timestamptz DEFAULT (now()),
  "expires_at" timestamptz NOT NULL
);

CREATE TABLE "two_factor_secrets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "secret_key" varchar,
  "recovery_codes" json
);

CREATE TABLE "two_factor_revocation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid,
  "revoked_at" timestamptz
);

CREATE TABLE "two_factor_backup_codes" (
  "user_id" uuid,
  "code" varchar
);

CREATE INDEX ON "password_reset_requests" ("email", "expires_at");


ALTER TABLE "password_reset_requests" ADD FOREIGN KEY ("email") REFERENCES "users" ("email");

ALTER TABLE "two_factor_secrets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "two_factor_revocation" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "two_factor_backup_codes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");