apiVersion: v1
kind: ConfigMap
metadata:
  name: go-auth-system-config
  namespace: go-auth-system
  labels:
    app.kubernetes.io/name: go-auth-system
    app.kubernetes.io/component: config
data:
  config.yaml: |
    server:
      rest:
        port: 8080
        host: "0.0.0.0"
        timeout: 30s
        cors:
          enabled: true
          allowed_origins: ["*"]
          allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          allowed_headers: ["*"]
      grpc:
        port: 9090
        host: "0.0.0.0"
        timeout: 30s
      metrics:
        port: 8081
        host: "0.0.0.0"
        path: "/metrics"
    
    database:
      host: postgres-service
      port: 5432
      name: auth_system
      ssl_mode: disable
      max_open_conns: 25
      max_idle_conns: 5
      conn_max_lifetime: 300s
    
    redis:
      host: redis-service
      port: 6379
      db: 0
      pool_size: 10
      min_idle_conns: 5
    
    security:
      password_hash:
        algorithm: argon2
        argon2:
          memory: 65536
          iterations: 3
          parallelism: 2
          salt_length: 16
          key_length: 32
        bcrypt:
          cost: 12
      
      token:
        type: jwt
        access_ttl: 15m
        refresh_ttl: 168h
      
      rate_limit:
        enabled: true
        requests_per_minute: 60
        burst_size: 10
        cleanup_interval: 60s
      
      encryption:
        algorithm: aes-256-gcm
    
    features:
      admin_dashboard: true
      monitoring: true
      audit_logging: true
      mfa:
        enabled: true
        totp: true
        sms: false
        email: true
        webauthn: true
      sso:
        saml: true
        oidc: true
        ldap: true
        oauth:
          google: true
          facebook: true
          github: true
    
    monitoring:
      prometheus:
        enabled: true
        path: "/metrics"
      logging:
        level: info
        format: json
      health_checks:
        enabled: true
        interval: 30s
    
    external:
      smtp:
        host: ""
        port: 587
        username: ""
        use_tls: true
      sms:
        provider: ""
        api_key: ""