global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "go-auth-system-alerts.yml"

scrape_configs:
  - job_name: 'go-auth-system'
    static_configs:
      - targets: ['app:8081']  # Using service name from docker-compose
    scrape_interval: 5s
    metrics_path: /metrics
    honor_labels: true

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093