apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-auth-system.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-auth-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database credentials
  DB_USER: {{ .Values.secrets.database.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.database.password | b64enc | quote }}
  
  # JWT configuration
  JWT_SIGNING_KEY: {{ .Values.secrets.jwt.signing_key | b64enc | quote }}
  JWT_ENCRYPTION_KEY: {{ .Values.secrets.jwt.encryption_key | b64enc | quote }}
  
  # Encryption
  ENCRYPTION_MASTER_KEY: {{ .Values.secrets.encryption.master_key | b64enc | quote }}
  
  # Redis password (if needed)
  REDIS_PASSWORD: {{ .Values.secrets.redis.password | default "" | b64enc | quote }}
  
  # External service credentials
  SMTP_PASSWORD: {{ .Values.secrets.external.smtp_password | b64enc | quote }}
  SMS_API_KEY: {{ .Values.secrets.external.sms_api_key | b64enc | quote }}
  
  # OAuth secrets
  OAUTH_GOOGLE_CLIENT_SECRET: {{ .Values.secrets.external.oauth.google_client_secret | b64enc | quote }}
  OAUTH_FACEBOOK_CLIENT_SECRET: {{ .Values.secrets.external.oauth.facebook_client_secret | b64enc | quote }}
  OAUTH_GITHUB_CLIENT_SECRET: {{ .Values.secrets.external.oauth.github_client_secret | b64enc | quote }}
  
  # SAML private key
  SAML_PRIVATE_KEY: {{ .Values.secrets.external.saml.private_key | b64enc | quote }}
  
  # LDAP bind password
  LDAP_BIND_PASSWORD: {{ .Values.secrets.external.ldap.bind_password | b64enc | quote }}