apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-auth-system.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-auth-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.http }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.ports.grpc }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: {{ .Values.service.ports.metrics }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "go-auth-system.selectorLabels" . | nindent 4 }}